In [ ]:
# one hot encoding representation
from tensorflow.keras.preprocessing.text import one_hot 

In [2]:
sentences = [
    "I love watching the sunset at the beach.",
    "The weather is pleasant today.",
    "She is reading a book in the library.",
    "He goes to the gym every morning.",
    "They are playing football in the park.",
    "The dog barked loudly at the stranger.",
    "My mother cooks delicious food.",
    "We are learning about machine learning.",
    "He bought a new laptop yesterday.",
    "The cat is sleeping on the sofa.",
    "I don’t like waking up early.",
    "She smiled when she saw the flowers.",
    "It is raining outside.",
    "The train is late again.",
    "He failed the test because he didn’t study.",
    "I want to become a data scientist.",
    "She dances beautifully.",
    "The movie was very boring.",
    "I forgot my umbrella at home.",
    "The baby is crying loudly."
]


In [15]:
voc_size=10000
one_hot_encoded=[one_hot(words,voc_size) for words in sentences]

In [16]:
one_hot_encoded

[[1434, 1513, 4087, 791, 6844, 2530, 791, 3559],
 [791, 8805, 7674, 5011, 7559],
 [7059, 7674, 3571, 9355, 1534, 7853, 791, 1591],
 [5981, 2185, 7676, 791, 1376, 4495, 9604],
 [2756, 9711, 5811, 4780, 7853, 791, 4665],
 [791, 3381, 1471, 5072, 2530, 791, 8930],
 [8522, 6836, 2467, 8500, 5727],
 [1973, 9711, 7711, 5114, 3398, 7711],
 [5981, 9948, 9355, 7036, 7280, 3718],
 [791, 6619, 7674, 8906, 5070, 791, 8802],
 [1434, 1376, 4156, 5225, 2658, 5016],
 [7059, 9265, 2263, 7059, 4085, 791, 8943],
 [3332, 7674, 9129, 3679],
 [791, 350, 7674, 1264, 3429],
 [5981, 9811, 791, 7188, 5622, 5981, 391, 3758],
 [1434, 6669, 7676, 6423, 9355, 8657, 5680],
 [7059, 8180, 5421],
 [791, 8145, 6026, 2164, 5035],
 [1434, 1532, 8522, 3163, 2530, 2719],
 [791, 5343, 7674, 9049, 5072]]

In [17]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences ## for same vector size input
from tensorflow.keras.models import Sequential
import numpy as np


In [18]:
sent_length=8

In [ ]:
embedded_docs=pad_sequences(one_hot_encoded,padding='pre',maxlen=sent_length)

In [20]:
embedded_docs

array([[1434, 1513, 4087,  791, 6844, 2530,  791, 3559],
       [   0,    0,    0,  791, 8805, 7674, 5011, 7559],
       [7059, 7674, 3571, 9355, 1534, 7853,  791, 1591],
       [   0, 5981, 2185, 7676,  791, 1376, 4495, 9604],
       [   0, 2756, 9711, 5811, 4780, 7853,  791, 4665],
       [   0,  791, 3381, 1471, 5072, 2530,  791, 8930],
       [   0,    0,    0, 8522, 6836, 2467, 8500, 5727],
       [   0,    0, 1973, 9711, 7711, 5114, 3398, 7711],
       [   0,    0, 5981, 9948, 9355, 7036, 7280, 3718],
       [   0,  791, 6619, 7674, 8906, 5070,  791, 8802],
       [   0,    0, 1434, 1376, 4156, 5225, 2658, 5016],
       [   0, 7059, 9265, 2263, 7059, 4085,  791, 8943],
       [   0,    0,    0,    0, 3332, 7674, 9129, 3679],
       [   0,    0,    0,  791,  350, 7674, 1264, 3429],
       [5981, 9811,  791, 7188, 5622, 5981,  391, 3758],
       [   0, 1434, 6669, 7676, 6423, 9355, 8657, 5680],
       [   0,    0,    0,    0,    0, 7059, 8180, 5421],
       [   0,    0,    0,  791,

In [22]:
# feature representation
dim=10

In [26]:
# RNN  model Creation

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 25ms/step


array([[[-4.54205275e-02, -4.67592143e-02,  1.17365122e-02, ...,
          2.21838020e-02,  8.44119862e-03,  1.90646686e-02],
        [ 2.59964503e-02,  1.54173635e-02,  8.60416889e-03, ...,
         -2.43776795e-02,  4.41820659e-02, -1.92962419e-02],
        [-2.01309845e-03,  3.62836979e-02, -2.33988892e-02, ...,
         -1.77209452e-03, -3.58599536e-02,  3.80843319e-02],
        ...,
        [ 3.09417397e-03,  2.15181373e-02, -4.71195355e-02, ...,
          1.56887881e-02, -8.53683800e-03, -1.11794099e-02],
        [ 1.17808804e-02, -4.47756052e-02,  2.28198618e-03, ...,
         -1.86382048e-02, -4.32948470e-02,  2.86632665e-02],
        [ 1.26204975e-02, -1.84919126e-02,  2.05767788e-02, ...,
         -4.42519560e-02, -2.55420450e-02, -2.71131881e-02]],

       [[-3.73732448e-02,  1.16707906e-02,  3.26936357e-02, ...,
         -1.37790814e-02, -4.97967601e-02,  2.12233104e-02],
        [-3.73732448e-02,  1.16707906e-02,  3.26936357e-02, ...,
         -1.37790814e-02, -4.97967601e

: 

In [30]:
embedded_docs[0]

array([1434, 1513, 4087,  791, 6844, 2530,  791, 3559])

In [29]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 70ms/step


array([[-0.04542053, -0.04675921,  0.01173651,  0.03528059, -0.02971457,
        -0.04560058,  0.00928602,  0.0221838 ,  0.0084412 ,  0.01906467],
       [ 0.02599645,  0.01541736,  0.00860417,  0.01935473,  0.03543473,
        -0.01786507,  0.01125177, -0.02437768,  0.04418207, -0.01929624],
       [-0.0020131 ,  0.0362837 , -0.02339889,  0.00186107,  0.0186731 ,
        -0.01816456,  0.02737042, -0.00177209, -0.03585995,  0.03808433],
       [ 0.01178088, -0.04477561,  0.00228199,  0.02671066,  0.04094378,
         0.00016882,  0.02430153, -0.0186382 , -0.04329485,  0.02866327],
       [-0.0249308 ,  0.00423225,  0.00689819, -0.00070424,  0.03030232,
         0.03758395, -0.01545936,  0.00045142, -0.00417478,  0.02340602],
       [ 0.00309417,  0.02151814, -0.04711954, -0.01161807, -0.02903156,
        -0.01993864,  0.04570657,  0.01568879, -0.00853684, -0.01117941],
       [ 0.01178088, -0.04477561,  0.00228199,  0.02671066,  0.04094378,
         0.00016882,  0.02430153, -0.0186382 